id:          DataAPICache
key:         DataAPICache
name:        Data API Cache
description: Provides request-level caching to the Data API.
author_name: Dan Wolfgang, Endevver
author_link: http://endevver.com
plugin_link: https://github.com/endevver/mt-plugin-data-api-cache
version:     1.0.0

callbacks:
    MT::App::DataAPI::init_app: $DataAPICache::DataAPICache::Plugin::init_app
